### ISSUE TITLE
Errors and warning during SQLite database creation

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#27]
@xrotwang While running through all the steps, I receive the following warnings and errors. Could you help me fix them?

Running cldfbench makecldf: 

```
(doreco) blum@lingn45 doreco % cldfbench makecldf cldfbench_doreco.py --glottolog-version v4.8
/Users/blum/Projects/venv/doreco/lib/python3.11/site-packages/clldutils/clilib.py:291: UserWarning: ImportError loading entry point doreco
  warnings.warn('ImportError loading entry point {0.name}'.format(ep))
WARNING Error importing doreco: No module named 'util'
INFO    running _cmd_makecldf on doreco ...
Path to clts data: ../../cldf_resources/clts
/Users/blum/Projects/venv/doreco/lib/python3.11/site-packages/csvw/utils.py:23: UserWarning: Invalid value for property: str
  warnings.warn('Invalid value for property: {}'.format(s))
  ```

Workaround: Ignore. Is this mac-specific, that the utils does not get loaded?
Also: We need to change the requirements for one package: `clldutils==3.20.0`(instead of 3.19.0)

--------------------
Running the SQLite conversion: 

```
(doreco) blum@lingn45 doreco % cldf createdb cldf/Generic-metadata.json doreco.sqlite
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 1357, in iterdicts
    res[col.header] = col.read(v, strict=strict)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 787, in read
    return datatype.read(v)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 631, in read
    return self.validate(self.parse(v))
                         ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 600, in parse
    return self.basetype.to_python(v, **self.derived_description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/datatypes.py", line 105, in to_python
    string.value_error(v)
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/datatypes.py", line 63, in value_error
    raise ValueError('invalid lexical value for {}: {}'.format(cls.name, v))
ValueError: invalid lexical value for string: CC BY-NC-ND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/cldf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycldf/__main__.py", line 30, in main
    return args.main(args) or 0
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycldf/commands/createdb.py", line 17, in run
    db.write_from_tg()
  File "/opt/homebrew/lib/python3.11/site-packages/pycldf/db.py", line 247, in write_from_tg
    items = {
            ^
  File "/opt/homebrew/lib/python3.11/site-packages/pycldf/db.py", line 248, in <dictcomp>
    tname: list(t.iterdicts())
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 1364, in iterdicts
    log_or_raise(
  File "/opt/homebrew/lib/python3.11/site-packages/csvw/metadata.py", line 192, in log_or_raise
    raise exception_cls(msg)
ValueError: cldf/contributions.csv:8:8 AnnotationLicense: invalid lexical value for string: CC BY-NC-ND
```

Workaround: Add "CC BY-NC-ND" manually to "cldf/Generic-metadata.json". But how can we do this automatically, during the cldf-conversion?

**Comment by xrotwang** [comment]
Ah, the license thing is straightforward. I just need to adapt the metadata.

Frederic Blum ***@***.***> schrieb am Di., 5. Dez. 2023,
12:06:
